// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Token string `json:"token"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserInfoReq struct {
	ID string `json:"id"`
}

type UserInfoResp struct {
	Name string `json:"name"`
}
