// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"
	"time"

	image "gozero_example/server/internal/handler/image"
	"gozero_example/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.CallLog},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/hello",
					Handler: helloHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.CallLog},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/image/flag",
					Handler: image.FlagHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(30000*time.Millisecond),
		rest.WithMaxBytes(10485760),
	)
}
