// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type HelloReq struct {
}

type HelloResp struct {
	Res interface{} `json:"res"`
}

type ImageFlagReq struct {
	ImageBase64 string  `json:"imageBase64"`
	ImageUrl    string  `json:"imageUrl"`
	Confidence  float64 `json:"confidence"`
}

type ImageFlagResp struct {
	Name       string  `json:"name"`
	Confidence float64 `json:"confidence"`
}
